---
# tasks file for nginx-setup

- name: install python 2
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Update Cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install nginx
  apt:
    name: nginx
    state: latest

- name: Create www directory
  file:
    path: /var/www/{{ domain }}
    state: directory
    mode: '0775'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy helloworld.com index.html
  template:
    src: index.html
    dest: /var/www/{{ domain }}/index.html
    owner: root
    group: root
    mode: '0644'

- name: Delete default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
#   state: present

- name: Copy nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: restart nginx
  service:
    name: nginx
    state: reloaded
#    become: yes 

- name: Copy nginx site.conf
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-enabled/{{ domain }}
    owner: root
    group: root
    mode: '0644'

- name: restart nginx
  service:
    name: nginx
    state: reloaded
